---
appveyor.yml:
  delete: true
".gitlab-ci.yml":
  delete: true
".travis.yml":
  stages:
    - static
    - spec
  deploy_to_forge:
    enabled: false
  simplecov: true
  docker_sets: []
  notifications:
    slack:
      secure: >-
        Q93Ymh6kE+zX2FWyy3JbEujQf0hTQu8US9EYVcU24kXS8YsluN/cQsE4cwjXT+FLVq96NofwMQDSj806uAqBm89tIP5+psw6vRG/vp03h1yFia4PYdtWmw4z+W2381krTCEWx16092j4wZ3BKqcsdCOGrsIJQX1prmQF/le4Xbi4fB5XAZdo9pxEtkZsn76ZnVk9Mu6a3YvQei5CXLATtVqD7JAlrnIvJs4XPl4BwpKP7n3jUTGpRSlu2ET/Lxfr3Kx5re6SKIY53hZJY/7WBKdOzhSDq4AfkgQajXV14RmMdhuW5zP5DKvRzP+bZf8pk/GfPEHYtlXlH+7y/ZXt0AaMbvoE0LpB3cZbBYKDxt7d9IzlYRm4+Y5FvzuKIu9DDGxsbrK7ukA/rsJoi1jaPdX4gkGHCIOvTdlAheecXKOwcdxgSGCYxS2aT0foV81y7nILK4ZJhS6ebp6x57Kx57GNjxyHXj3Fc5wL6dcIKQdBWO9eMSoUb2m9OYpievgJgsHValwXZc1cuDSBzdp1Q5tYIjsVdawc/vUFVTgPcp+xRxVqFkZ59uC9blUpRytiKtCPI9WH4BwAEi8Ifuu0AjJQsMEpqnTFBgPCcSyKZdO0wAH093mBvDOp24Pqqp7MSKD818SzbtUy1ScZ4E7xgxnRvQeeSKykQ5cuqNbIE0w=
".rubocop.yml":
  include_todos: true
Gemfile:
  optional:
    ":development":
    - gem: rbvmomi
    - gem: hocon
    - gem: retries
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
    ":acceptance":
    - gem: mustache
      version: 0.99.8
Rakefile:
  changelog_since_tag: 'v1.4.0'
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
spec/spec_helper.rb:
  mock_with: ':rspec'
.github/workflows/auto_release.yml:
  unmanaged: false
